name: OrbitPoint
options:
  bundleIdPrefix: com.davidbond
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.9"
    TARGETED_DEVICE_FAMILY: "1"
    INFOPLIST_KEY_UILaunchScreen_Generation: YES
    INFOPLIST_KEY_UISupportedInterfaceOrientations: UIInterfaceOrientationPortrait
    INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor

targets:
  OrbitPoint:
    type: application
    platform: iOS
    sources:
      - OrbitPoint
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.davidbond.orbitpoint
        INFOPLIST_KEY_CFBundleDisplayName: OrbitPoint
    entitlements:
      path: OrbitPoint/OrbitPoint.entitlements
      properties:
        com.apple.developer.game-center: true
    info:
      path: OrbitPoint/Info.plist
      properties:
        CFBundleDisplayName: OrbitPoint
        UILaunchScreen: {}
        GKSupportsGameCenterLive: true
